# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-13 17:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_auto_20191106_1748'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Player',
        ),
        migrations.AlterField(
            model_name='message',
            name='likes',
            field=models.ManyToManyField(related_name='messages_liked', to='logreg.User'),
        ),
        migrations.AlterField(
            model_name='message',
            name='poster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='logreg.User'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
